language: node_js
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8.3'
before_script:
  - npm prune && npm cache clean
script:
  - npm run test